#ifndef COLOR_PICKER_RESOURCE_H
#define COLOR_PICKER_RESOURCE_H

// resources 
#define IDI_PICKER		101
#define IDI_CURSOR		102

#define	IDD_COLOR_PICKER_POPUP		2100
#define	IDC_COLOR_PALETTE			(IDD_COLOR_PICKER_POPUP + 1)
#define IDC_COLOR_TEXT				(IDD_COLOR_PICKER_POPUP + 2)
#define ID_PICK						(IDD_COLOR_PICKER_POPUP + 3)
#define ID_MORE						(IDD_COLOR_PICKER_POPUP + 4)
#define IDC_OLD_COLOR				(IDD_COLOR_PICKER_POPUP + 5)
#define IDC_NEW_COLOR				(IDD_COLOR_PICKER_POPUP + 6)
#define IDC_COLOR_BG				(IDD_COLOR_PICKER_POPUP + 7)

#define	IDD_SCREEN_PICKER_POPUP		2200
#define IDC_SCR_COLOR_HEX			(IDD_SCREEN_PICKER_POPUP + 1)
#define IDC_SCR_COLOR_RGB			(IDD_SCREEN_PICKER_POPUP + 2)


// messages
#define WM_QCP_BASE					WM_USER + 100
#define WM_QCP_PICK					(WM_QCP_BASE + 1)
#define WM_QCP_HOVER				(WM_QCP_BASE + 2)
#define WM_QCP_CANCEL				(WM_QCP_BASE + 3)
#define WM_QCP_START_SCREEN_PICKER	(WM_QCP_BASE + 4)
#define WM_QCP_END_SCREEN_PICKER	(WM_QCP_BASE + 5)
#define WM_QCP_SCREEN_HOVER			(WM_QCP_BASE + 6)
#define WM_QCP_SCREEN_PICK			(WM_QCP_BASE + 7)
#define WM_QCP_SCREEN_CANCEL		(WM_QCP_BASE + 8)

#endif //COLOR_PICKER_RESOURCE_H
