#ifndef COLOR_PICKER_RESOURCE_H
#define COLOR_PICKER_RESOURCE_H

// resources 
#define IDI_PICKER		101
#define IDI_CURSOR		102

#define	IDD_COLOR_PICKER_POPUP		2100
#define IDC_COLOR_TEXT				(IDD_COLOR_PICKER_POPUP + 1)
#define ID_PICK						(IDD_COLOR_PICKER_POPUP + 2)
#define ID_MORE						(IDD_COLOR_PICKER_POPUP + 3)

#define	IDD_SCREEN_PICKER_POPUP		2200
#define IDC_SCR_COLOR_HEX			(IDD_SCREEN_PICKER_POPUP + 1)
#define IDC_SCR_COLOR_RGB			(IDD_SCREEN_PICKER_POPUP + 2)


// messages
#define WM_QCP_BASE					WM_USER + 100
#define WM_QCP_PICK					(WM_QCP_BASE + 1)
#define WM_QCP_HOVER				(WM_QCP_BASE + 2)
#define WM_QCP_CANCEL				(WM_QCP_BASE + 3)
#define WM_QCP_DEACTIVATE			(WM_QCP_BASE + 4)
#define WM_QCP_START_SCREEN_PICKER	(WM_QCP_BASE + 5)
#define WM_QCP_END_SCREEN_PICKER	(WM_QCP_BASE + 6)
#define WM_QCP_SCREEN_HOVER			(WM_QCP_BASE + 7)
#define WM_QCP_SCREEN_PICK			(WM_QCP_BASE + 8)
#define WM_QCP_SCREEN_CANCEL		(WM_QCP_BASE + 9)


// ui stuff
#define CONTROL_PADDING 6

#define PALETTE_X CONTROL_PADDING
#define PALETTE_Y CONTROL_PADDING
#define PALETTE_ROW 14
#define PALETTE_COLUMN 24
#define PALETTE_CELL_SIZE 12
#define PALETTE_WIDTH (PALETTE_COLUMN * PALETTE_CELL_SIZE)
#define PALETTE_HEIGHT (PALETTE_ROW * PALETTE_CELL_SIZE)

#define RECENT_ZONE_ROW 2
#define RECENT_ZONE_COLUMN 8

#define ADJUST_ZONE_X (PALETTE_X + PALETTE_WIDTH + CONTROL_PADDING)
#define ADJUST_ZONE_Y CONTROL_PADDING
#define ADJUST_ZONE_ROW 11
#define ADJUST_ZONE_CELL_WIDTH 12
#define ADJUST_ZONE_CELL_HEIGHT 12
#define ADJUST_ZONE_WIDTH (ADJUST_ZONE_CELL_WIDTH*4+3)
#define ADJUST_ZONE_HEIGHT (ADJUST_ZONE_CELL_HEIGHT*ADJUST_ZONE_ROW)

#define SWATCH_X ADJUST_ZONE_X
#define SWATCH_Y (ADJUST_ZONE_Y + ADJUST_ZONE_HEIGHT + CONTROL_PADDING)
#define SWATCH_WIDTH (ADJUST_ZONE_WIDTH/2)
#define SWATCH_HEIGHT (PALETTE_HEIGHT - ADJUST_ZONE_HEIGHT - CONTROL_PADDING)

#define BUTTON_X CONTROL_PADDING
#define BUTTON_Y (PALETTE_HEIGHT + CONTROL_PADDING*2 + 1)
#define BUTTON_WIDTH 32
#define BUTTON_HEIGHT 32

#define TEXT_X (BUTTON_X + BUTTON_WIDTH*2 + CONTROL_PADDING*2)
#define TEXT_Y (BUTTON_Y + (BUTTON_HEIGHT-12)/2)
#define TEXT_WIDTH (POPUP_WIDTH-TEXT_X-CONTROL_PADDING)
#define TEXT_HEIGHT 16

#define POPUP_WIDTH (PALETTE_WIDTH + ADJUST_ZONE_WIDTH + CONTROL_PADDING*3 +  2)
#define POPUP_HEIGHT (PALETTE_HEIGHT + BUTTON_HEIGHT + CONTROL_PADDING*3 + 2)

#define CONTROL_BORDER_COLOR 0x666666

#endif //COLOR_PICKER_RESOURCE_H
